### ISSUE TITLE
filename not extracted properly

### ISSUE THREAD

**Issue by daniel-onisoru** [skydiscover/ffmpeg-jobs-docker#1]
Unless I'm missing something the line 50 should be:

`VIDEOINPUT=$(echo "${FF_OPTS}" | perl -ne 'print "$1\n" if /-i +\"([^\"]*)\"/')`

otherwise it doesn't work for the example job because -i "file" is the first thing in FF_OPTS

**Comment by skydiscover** [comment]
You, good sir, are totally right, but since the input is not necessarily the first argument either, I will replace the line with
`VIDEOINPUT=$(echo "${FF_OPTS}" | perl -ne 'print "$1\n" if /\b(?:.* )?-i +\"([^\"]*)\"/')`

That should do the trick.
Anyhow, thanks a lot for the input.
